[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    ottowinter/ESPAsyncWebServer-esphome @ ^3.1.0
    esphome/AsyncTCP-esphome @ ^2.1.1
    waspinator/AccelStepper @ ^1.64
    madhephaestus/ESP32Servo @ ^1.1.0